config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'photos#index'

  resources :users, only: :show do
    resources :photos, only: :create
  end

  resources :photos, only: [:show, :destroy] do
    resources :comments, only: :create
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  has_attached_file :image, styles: {medium: '640x320', thumb: '100x100' },
    url: '/assets/images/:id/:style/:basename.:extension'
  validates_attachment_presence :image
  validates_attachment_content_type :image, content_type: ['image/jpeg', 'image/png']

  validates :user, presence: true
  validates :title, presence: true

  before_create { 
    self.views = 0
    self.uploaded_on = Time.now.utc
  }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :photos
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    photo = Photo.find(params[:photo_id])
    comment = photo.comments.new(comment_params)
    comment.user = current_user
    comment.save
    redirect_to photo
  end

  private
    def comment_params
      params.require(:comment).permit(:text)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def index
    @photos = Photo.order(:views)
  end

  def create
    @new_photo = current_user.photos.new(photo_params)
    if @new_photo.save
      redirect_to @new_photo.user
    else
      @user = current_user
      render '/users/show'
    end
  end

  def show
    @photo = Photo.find(params[:id])
    @photo.views = @photo.views + 1
    @photo.save
  end

  def destroy
    Photo.find(params[:id]).destroy
    redirect_to current_user
  end

  private
    def photo_params
      params.require(:photo).permit(:image, :title)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @new_photo = Photo.new
    @new_photo.user = @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Image Boards</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id='top-bar'>
    <%= link_to 'home', root_path, class: 'barred' %>
    <% if user_signed_in? %>
      <%= link_to current_user.email, current_user, class: 'barred'%>
      <%= link_to 'sign out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'sign in', new_user_session_path, class: 'barred' %> 
      <%= link_to 'sign up', new_user_registration_path %>
    <% end %>
  </div>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/photos/index.html.erb
<div id='gallery'>
    <% if @photos.empty? %>

      <p> There are no photos yet! come back later or 
        <% if user_signed_in? %>
          <%= link_to 'click here', current_user %> to upload your own. </p> 
    <% else %>
      <%= link_to 'login', new_user_session %> to upload your own. </p> 
    <% end %>
    <% else %>
      <% @photos.each do |photo| %>
        <%= link_to photo, class: 'thumbnail' do %>
          <%= image_tag photo.image.url(:thumb) %>
        <% end %>
      <% end %>
    <% end %>
</div>

app/views/photos/show.html.erb
<div id='image-strip'>
  <% if @photo.user == current_user %>
  <%= button_to 'delete', photo_path(@photo), method: :delete, class: 'delete-button' %>
<% end %>
<h2>
  <%= @photo.title %><br/>
  <span class='timestamp'>uploaded <%= distance_of_time_in_words(@photo.uploaded_on, Time.now) %></span>
</h2>
  <%= image_tag @photo.image.url(:medium), class: 'image-panel' %>
  <p class='timestamp'><%= pluralize(@photo.views, 'views')%></p>

  <% if user_signed_in? %>
    <%= form_for [@photo, @photo.comments.new] do |f| %>
      <p>
      <span class='commenter'><%= current_user.email %></span><br/>
      <%= f.text_area :text, placeholder: 'Leave a comment...', class: 'comment-area' %>
      </p>
      <%= f.submit 'Comment' %>
    <% end %>
  <% else %>
    <p> <%= link_to 'Log in', new_user_session_path %> to leave a comment</p>
  <% end %>

  <hr/>
  <% @photo.comments.all.each do |comment| %>
    <p >
    <span class='commenter'><%= comment.user.email %></span><br/>
    <span class='comment'><%= comment.text %></span>
    </p>
  <% end %>
</div>

app/views/users/show.html.erb
<div id='content'>
  <div id='images'>
    <h4> <%= pluralize(@user.photos.length, 'image') %> </h4>
    <% if @user.photos.empty? %>
      <p> You have no photos yet! Upoad your first photo to get started. </p>
    <% else %>
      <% @user.photos.each do |photo| %>
        <%= link_to photo, class: 'thumbnail' do %>
          <%= image_tag photo.image.url(:thumb) %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div id='upload'>
    <h4> Upload new image </h4>
    <%= form_for([@user, @new_photo], html: { multipart: true }) do |f| %>

      <% if @new_photo.errors.any? %>
        <div class='errors'>
            <% @new_photo.errors.full_messages.each do |msg| %>
              <p>- <%= msg %></p>
            <% end %>
        </div>
      <% end %>

      <p>
      <%= f.label 'Title' %><br />
      <%= f.text_field :title %>
      </p>

      <p>
      <%= f.label 'Image' %><br />
      <%= f.file_field :image %>
      </p>

      <%= f.submit 'Upload' %>

    <% end %>
  </div>
</div>